---
title: "Analysis SIP Emilio"
author: "Gust Bilcke"
date: "17 augustus 2018"
output: html_document
---

# Import data
```{r include=FALSE}
library(edgeR) ; library(stageR) ; library(tximport) ; library(readr) ;library(xlsx);library(ggplot2); library(xlsx)

wd <- getwd()
dir <- dirname(dirname(wd))

load(paste0(dir,"/Metadata/tx2gene.rda"))

quantFiles = list.files(paste0(dir, "/Mapping_output_Salmon/Mapping_Cirri/"))
data <- tximport(files = paste0(dir, "/Mapping_output_Salmon/Mapping_Cirri/", quantFiles, "/quant.sf"), type = "salmon", txOut = F, tx2gene = tx2gene, importer = read_tsv)

counts <- as.data.frame(data$counts)
colnames(counts) = quantFiles
meta <- c("control", "control", "control", "SIP", "SIP", "SIP")

```

# filter and normalize
```{r}

# Save unfiltered CPMs
dtje <- DGEList(counts)
cpmpje <- cpm(dtje)
write.table(cpm(dtje), "cpm_Emilio_no_filtering.txt", quote =F)

keep <- rowSums(cpm(counts)>1)>=3
table(keep)
counts <- counts[keep,]

d <- DGEList(counts)
d <- calcNormFactors(d)
```
# model design
```{r}
design <- model.matrix(~ meta )

```

# MDS plot
```{r}
t<- plotMDS(d)

MDS_df <- data.frame(t$x, t$y)

ggplot(data = MDS_df) +
  geom_point(aes(x = t.x, y = t.y,  fill = meta), size = 3, shape = 21)  +
  theme_classic() +
  theme(legend.box="horizontal") +
  scale_fill_manual(values= c("grey20",  "cyan4")) +
  guides(fill = guide_legend(override.aes=list(shape=21)), shape = guide_legend(override.aes=list(fill = "black"))) +
  theme(legend.position = c(0.5, 0.55)) +
  labs(fill = "Treatment") +
  xlab("Leading logFC dim1") +
  ylab("Leading logFC dim2")
```

# model fitting
```{r}

d <- estimateDisp(d,design)
plotBCV(d)

fit <- glmFit(d,design)

# check if the residuals follow a negative binomial distribution (Q-Q plot)
gofStat <- gof(fit,plot=TRUE) # not so good
```
# testing
```{r}
LRT <- glmLRT(fit, coef = 2)

p <- LRT$table$PValue
adjP <- p.adjust(p, method = "BH")
LFC <- LRT$table$logFC
result <- rep(0, length(LFC))
result[adjP < 0.05] <- 1

names(p) <- rownames(LRT$table)
names(adjP) <- rownames(LRT$table)
names(LFC) <- rownames(LRT$table)
names(result) <- rownames(LRT$table)

cpm <- as.data.frame(cpm(d))
colnames(cpm) <- rownames(d$samples)

table(result)
```

```{r}
#################
# volcano plot
#################
 ggplot() +
  geom_point(aes( x=LFC, y= -log10(adjP), colour = as.factor(result)), size = 0.7)+
  labs(col="significant") +
  theme_bw()

```